### ISSUE TITLE
DCPing a hub return errors

### ISSUE THREAD

**Issue by Kcchouette** [direct-connect/go-dcpp#27]
```
# ./dcping ping dchub://XXXXXXXXXXX:1209
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x77d671]

goroutine 1 [running]:
main.init.0.func3(0xc0000acc80, 0xc000058f00, 0x1, 0x1, 0x0, 0x0)
	/root/go-dcpp/cmd/dcping/main.go:112 +0x921
github.com/spf13/cobra.(*Command).execute(0xc0000acc80, 0xc000058ed0, 0x1, 0x1, 0xc0000acc80, 0xc000058ed0)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc48400, 0xc00002c37c, 0xc0000d1f88, 0x40737f)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/root/go-dcpp/cmd/dcping/main.go:27 +0x32
```

## Some more infos
- Hub is online → yes
- IP is banned → I can do a "normal" ping
- software of the hub → PtokaX

**Comment by dennwc** [comment]
Thanks for reporting it! Fixed upstream.
